import '../scss/styles.scss';
import '../js/main.js';
import '../js/selectorStylize.js';
import '../js/slider.js';
import '../js/smoothScroll.js';
import '../js/pickaday.js';
import '../js/slick.js';
import '../js/ajax-events.js';
import '../js/ajax-form.js';